#!/usr/bin/python3
from collections import Counter
import operator
import requests


def count_words(subreddit, word_list, hot=[], after=None):
    url = 'http://reddit.com/r/{}/hot.json'
    header = {'User-agent': 'El Rayi hace pruebas'}
    limit = {'limit': 100}
    if isinstance(after, str):
        if after != 'STOP':
            limit['after'] = after
        else:
            # Base case
            # word_list = [x.lower() for x in word_list]
            # word_list = [(word_list)].sort()
            # pre_imp = {k: v for k, v in zip(word_list, [0] * len(word_list))}
            # cuenta = Counter(hot)
            # for k, v in pre_imp.items():
            #     if cuenta.get(k):
            #         pre_imp[k] = cuenta.get(k)
            # impre = sorted(pre_imp.items(), key=operator.itemgetter(1), reverse=True)
            # for i in impre:
            #     a, b = i
            #     if b > 0:
            #         print('{}: {}'.format(a, b))
            return hot

    # Recursive case
    resp = requests.get(url.format(subreddit), headers=header, params=limit)
    if resp.status_code != 200:
        return None
    data = resp.json().get('data', {})
    after = data.get('after', 'STOP')
    if not after:
        after = 'STOP'
    
    hot = hot + [post.get('data', {}).get('title') for post in data.get('children', [])]
    print(hot)
    return count_words(subreddit, hot, after)
